### ISSUE TITLE
Start Endpoint

### ISSUE THREAD

**Issue by tardisman5197** [tardisman5197/barnes-hut-sim#10]
Implement the start simulation endpoint.

This should start a simulation that exists for the specified number of steps.

**Comment by tabarnhack** [comment]
I'm glad if I can contribute to this issue! Can you assign it to me, please? I'll be working on it.

**Comment by tardisman5197** [comment]
If there is anything I could help with give me a shout.

There should be a starting point for this in `/cmd/server/api/endpoints.go`

**Comment by tabarnhack** [comment]
No problem! I had a quick peek and I found what to do.

I just have a few questions about API communication with the client. 
Do errors have to be reported through JSON via an error field?
What pieces of information have to be logged to the terminal?

**Comment by tardisman5197** [comment]
Nah, I don't think it is necessary to report any errors with JSON, as long as an appropriate error response code is sent.
I would probably just send a plain text error description.

As for logging to the terminal, anything you think might be useful.
I will probably create an issue to use a logging library for the whole project later on.

**Comment by tabarnhack** [comment]
Ok I understand.

About the results return, does the API has to send every step status or just the last one?
If the first choice is chosen, the `simulation` package will need some changes so I can retrieve enough pieces of information.

**Comment by tardisman5197** [comment]
For the results endpoint, I was thinking just the last step. You could just call the start endpoint for every step.

But it might be better to send all of the steps. However the return JSON might be pretty big if the number of steps is really high.
