### ISSUE TITLE
Status Endpoint

### ISSUE THREAD

**Issue by tardisman5197** [tardisman5197/barnes-hut-sim#11]
Implement the status endpoint.

This endpoint should return the status of a specified simulation.
By status I mean if it is currently running or idle and some basic information about the simulation, such as step number.

**Comment by nanikjava** [comment]
Was looking into the code and noticed that the following

```
type API struct {
	server *http.Server

	mutex       *sync.RWMutex
	simulations map[string]simulation.Simulation
}
```

in order to implement the status functionality to report the steps the `simulations` field should be declared as 

```
simulations map[string]*simulation.Simulation
```

so that when the `Steps` method is called inside goroutine the Simulation object will be updated accordingly (the steps).

**Comment by tardisman5197** [comment]
Yeah, that would be one way of doing it.
Another way could be storing the status of the simulations in another map.

**Comment by nanikjava** [comment]
@tardisman5197 PR submitted. Thanks.
