### ISSUE TITLE
Improve Readme

### ISSUE THREAD

**Issue by tardisman5197** [tardisman5197/barnes-hut-sim#15]
Make the Readme better.

**Comment by misslorsx** [comment]
What would you like adding to the readme? is there anything specific? like a stats icon?

**Comment by tardisman5197** [comment]
Nothing specific really.
I guess it just needs to be a little more descriptive, I imagine it would follow some of the common templates found on GitHub.

Anything is an improvement on what it currently is.

**Comment by misslorsx** [comment]
Ok great, mind if I contribute?

**Comment by tardisman5197** [comment]
No not at all, thanks
